# -*- coding: utf-8 -*-
"""2702378501-Rafly Athallah Khansa Putra-Numpy.linalg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8R254FHTsUc09VzSm66dWLEeYK-dt3U

**Use numpy.linalg.solve**
"""

import numpy as np

A = np.array([[4,3,-5],
              [-2,-4,5],
              [8,8,0]])
y = np.array([2,5,-3])

x = np.linalg.solve(A, y)
print(x)

"""**Using the matrix inversion approach**"""

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)